name: Build .NET Core project and deploy to SmarterASP.NET
on: [push]

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # or your preferred version (3.1.x, 5.0.x, 7.0.x, etc.)

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish --configuration Release --no-build --output ./publish

      - name: Deploy to SmarterASP.NET via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win1232.site4now.net
          username: abcd_test
          password: as5562569
          local-dir: ./publish/
          server-dir: / # or your specific directory on the server
